"""Add environment segregation for API keys and provider credentials

Revision ID: env_segregation_001
Revises: add_api_key_rotation
Create Date: 2025-12-25 15:41:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'env_segregation_001'
down_revision: Union[str, None] = 'add_api_key_rotation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add environment column to api_keys if not exists
    # Note: This already exists from previous migration, but we'll ensure it's here
    if not op.column_exists('api_keys', 'environment'):
        op.add_column('api_keys', sa.Column('environment', sa.String(), nullable=True))
        # Set default environment for existing keys
        op.execute("UPDATE api_keys SET environment = 'test' WHERE environment IS NULL")
        op.alter_column('api_keys', 'environment', nullable=False)
    
    # Add unique constraint for (user_id, environment, key_hash)
    op.create_unique_constraint(
        'uq_api_keys_user_env_hash',
        'api_keys',
        ['user_id', 'environment', 'key_hash']
    )
    
    # Ensure provider_credentials has environment column (should already exist)
    if not op.column_exists('provider_credentials', 'environment'):
        op.add_column('provider_credentials', sa.Column('environment', sa.String(), nullable=True))
        # Set default environment for existing credentials
        op.execute("UPDATE provider_credentials SET environment = 'test' WHERE environment IS NULL")
        op.alter_column('provider_credentials', 'environment', nullable=False)
    
    # Update unique constraint for provider_credentials
    # First drop existing constraint if it exists
    try:
        op.drop_constraint('uq_provider_credentials_user_provider_env', 'provider_credentials', type_='unique')
    except:
        pass  # Constraint might not exist
    
    # Create new constraint
    op.create_unique_constraint(
        'uq_provider_credentials_user_provider_env',
        'provider_credentials',
        ['user_id', 'provider_name', 'environment']
    )
    
    # Ensure transaction_logs has environment column (should already exist)
    if not op.column_exists('transaction_logs', 'environment'):
        op.add_column('transaction_logs', sa.Column('environment', sa.String(), nullable=True))
        # Set default environment from associated API key
        op.execute("""
            UPDATE transaction_logs 
            SET environment = COALESCE(
                (SELECT environment FROM api_keys WHERE api_keys.id = transaction_logs.api_key_id),
                'test'
            )
            WHERE environment IS NULL
        """)
        op.alter_column('transaction_logs', 'environment', nullable=False)
    
    # Create index for environment-based queries
    op.create_index('idx_api_keys_env_active', 'api_keys', ['environment', 'is_active'], unique=False)
    op.create_index('idx_provider_credentials_env_active', 'provider_credentials', ['environment', 'is_active'], unique=False)
    op.create_index('idx_transaction_logs_env_created', 'transaction_logs', ['environment', 'created_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index('idx_transaction_logs_env_created', table_name='transaction_logs')
    op.drop_index('idx_provider_credentials_env_active', table_name='provider_credentials')
    op.drop_index('idx_api_keys_env_active', table_name='api_keys')
    
    op.drop_constraint('uq_provider_credentials_user_provider_env', 'provider_credentials', type_='unique')
    op.drop_constraint('uq_api_keys_user_env_hash', 'api_keys', type_='unique')
    
    # Note: We keep the environment columns to avoid data loss in downgrade
    
    # ### end Alembic commands ###